### ISSUE TITLE
Structs instead of Dicts?

### ISSUE THREAD

**Issue by PCrompton** [danielbreves/MusicTheory#4]
I'm wondering if it would be beneficial to change the design for mapping scales, chords, etc., from dictionaries to structs. What do you think?

I'm using Xcode 8.1 and Swift 3.

**Comment by danielbreves** [comment]
IMO dictionaries are the right construct for these, since we're representing collections that we could possibly want to iterate over. Any reason why you think structs would be better?

**Comment by PCrompton** [comment]
I think it would be easier to use if the user was able to call, for instance `c.scale.major` and it would return an instance of RootWithIntervals. I did a little fooling around on a local branch and created a `Scales` struct which allowed me to do that.  I'm new to software development though so take my opinion with a grain of salt.
