### ISSUE TITLE
Is your circle of fifths definition correct?

### ISSUE THREAD

**Issue by modelarious** [danielbreves/MusicTheory#7]
public static let CircleOfFifths = [
    "major": ["C", "G", "D", "A", "E", "B", "F♯", "C♯", "F", "B♭", "E♭", "A♭", "D♭", "G♭", "C♭"],
    "minor": ["A", "E", "B", "F♯", "C♯", "G♯", "D♯", "A♯", "D", "G", "C", "F", "B♭", "E♭", "A♭"]
  ]

In your definition, it goes from B to F#, a fifth, F# then moves to C#, a fifth, C# then moves to F, a major third

**Comment by danielbreves** [comment]
[Fixed](https://github.com/danielbreves/MusicTheory/commit/5933dc185c2d81cff7dd93c843d4ee6262f92f9a)! Thanks!
